# @package _global_

defaults:
  - _self_
  - data: default
  - model: resnet
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
