# @package _global_

defaults:
  - _self_
  - data: artifact
  - model: artifact
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /home/max/nulp/it-jim/BinaryImageClassifier/logs/train/runs/2025-04-10_15-54-36/checkpoints/epoch_018.ckpt
