# @package _global_

defaults:
  - _self_
  - data: artifact
  - model: artifact
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "inference"

# Path to the image file to predict
image_path: ???

# Path to the model checkpoint
ckpt_path: ???
